/**
 * SentimentITAPanel — V14.0 舆情ITA引擎面板
 * 3个Tab: 舆情监测 | ITA触发链路 | 补偿方案生成
 *
 * 核心机制:
 * - 情绪优先 (Sentiment-First): 情绪密度超标 → Draft Hold
 * - 责任上移 (Escalate-Up): 自动上报总部,不断开连接
 * - 1小时补偿方案 + 48小时调查报告
 */

import React, { useState, useEffect } from 'react';
import {
  Box, Card, CardContent, Typography, Grid, Chip,
  Table, TableBody, TableCell, TableContainer, TableHead,
  TableRow, Paper, Button, Alert, LinearProgress,
  Tabs, Tab, Divider, IconButton, Tooltip,
  Switch, FormControlLabel, Slider, Select, MenuItem,
} from '@mui/material';
import ApiIcon from '@mui/icons-material/Api';
import PriorityHighIcon from '@mui/icons-material/PriorityHigh';
import ShieldIcon from '@mui/icons-material/Shield';
import TimelineIcon from '@mui/icons-material/Timeline';
import ReportIcon from '@mui/icons-material/Report';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import ErrorIcon from '@mui/icons-material/Error';
import WarningIcon from '@mui/icons-material/Warning';
import SentimentVeryDissatisfiedIcon from '@mui/icons-material/SentimentVeryDissatisfied';
import SentimentSatisfiedIcon from '@mui/icons-material/SentimentSatisfied';
import apiClient from '../services/api';

// =============== Types ===============

interface SentimentAlert {
  alertId: string;
  agentId: string;
  polarity: 'NEGATIVE' | 'NEUTRAL' | 'POSITIVE';
  intensity: number;       // 0-100
  velocity: number;        // 传播速度
  platform: string;
  keywords: string[];
  draftHoldTriggered: boolean;
  escalateTriggered: boolean;
  compensateDue: number;   // 补偿方案剩余秒数
  reportDue: number;       // 调查报告剩余秒数
  status: 'MONITORING' | 'DRAFT_HOLD' | 'ESCALATED' | 'COMPENSATED' | 'RESOLVED';
  createdAt: number;
}

interface ITATriggerChain {
  chainId: string;
  information: {
    type: string;
    source: string;
    watchKey: string;
    currentValue: number;
  };
  trigger: {
    expression: string;
    thresholdType: string;
    thresholdValue: number;
    currentValue: number;
    fired: boolean;
  };
  actions: Array<{
    id: string;
    type: string;
    status: string;
    result?: string;
  }>;
  status: 'PENDING' | 'FIRING' | 'COMPLETED' | 'VETOED';
}

interface CompensatePlan {
  planId: string;
  alertId: string;
  agentId: string;
  compensateType: 'REFUND' | 'COUPON' | 'APOLOGY' | 'UPGRADE' | 'CUSTOM';
  amount?: number;
  description: string;
  autoGenerated: boolean;
  approved: boolean;
  executed: boolean;
  feedbackScore?: number;
}

interface SentimentStats {
  totalAlerts: number;
  alertsByPolarity: Record<string, number>;
  draftHoldCount: number;
  escalatedCount: number;
  avgResponseTime: number;    // 平均响应时间(秒)
  compensateSuccessRate: number;
  falsePositiveRate: number;
}

// =============== Sub-Components ===============

/** 舆情监测Tab */
const MonitoringTab: React.FC = () => {
  const [alerts, setAlerts] = useState<SentimentAlert[]>([]);
  const [stats, setStats] = useState<SentimentStats | null>(null);
  const [loading, setLoading] = useState(false);
  const [polarityFilter, setPolarityFilter] = useState<string>('ALL');

  const fetchData = async () => {
    setLoading(true);
    try {
      const [alertsRes, statsRes] = await Promise.all([
        apiClient.get('/v14/sentiment-ita/alerts'),
        apiClient.get('/v14/sentiment-ita/stats'),
      ]);
      if (alertsRes.data?.code === 0) setAlerts(alertsRes.data.data || []);
      if (statsRes.data?.code === 0) setStats(statsRes.data.data);
    } catch (err) {
      console.error('Failed to fetch sentiment data:', err);
    }
    setLoading(false);
  };

  useEffect(() => { fetchData(); }, []);

  const filtered = polarityFilter === 'ALL' ? alerts :
    alerts.filter(a => a.polarity === polarityFilter);

  const getPolarityColor = (p: string) => {
    if (p === 'NEGATIVE') return '#f44336';
    if (p === 'POSITIVE') return '#4caf50';
    return '#ff9800';
  };

  const getStatusColor = (s: string) => {
    if (s === 'RESOLVED') return 'success';
    if (s === 'ESCALATED') return 'error';
    if (s === 'DRAFT_HOLD') return 'warning';
    return 'default';
  };

  return (
    <Box>
      {stats && (
        <Grid container spacing={2} sx={{ mb: 2 }}>
          {[
            { label: '总预警', value: stats.totalAlerts, icon: <ReportIcon />, color: '#1976d2' },
            { label: '负面情绪', value: stats.alertsByPolarity?.NEGATIVE || 0, icon: <SentimentVeryDissatisfiedIcon />, color: '#f44336' },
            { label: 'Draft Hold', value: stats.draftHoldCount, icon: <WarningIcon />, color: '#ff9800' },
            { label: '已上报', value: stats.escalatedCount, icon: <PriorityHighIcon />, color: '#9c27b0' },
            { label: '平均响应(分)', value: (stats.avgResponseTime / 60).toFixed(1), icon: <TimelineIcon />, color: '#009688' },
          ].map((item, idx) => (
            <Grid item xs={6} md={2.4} key={idx}>
              <Card><CardContent sx={{ textAlign: 'center', py: 1.5 }}>
                <Box sx={{ color: item.color, mb: 0.5 }}>{item.icon}</Box>
                <Typography variant="h6">{item.value}</Typography>
                <Typography variant="caption" color="text.secondary">{item.label}</Typography>
              </CardContent></Card>
            </Grid>
          ))}
        </Grid>
      )}

      <Box sx={{ mb: 2, display: 'flex', gap: 1 }}>
        {['ALL', 'NEGATIVE', 'NEUTRAL', 'POSITIVE'].map(p => (
          <Chip key={p} label={p} onClick={() => setPolarityFilter(p)}
            color={polarityFilter === p ? 'primary' : 'default'} size="small" />
        ))}
        <Button size="small" onClick={fetchData} disabled={loading}>刷新</Button>
      </Box>

      {loading ? <LinearProgress /> : (
        <TableContainer component={Paper} sx={{ maxHeight: 500, overflow: 'auto' }}>
          <Table size="small" stickyHeader>
            <TableHead>
              <TableRow>
                <TableCell>Alert ID</TableCell>
                <TableCell>Agent</TableCell>
                <TableCell>极性</TableCell>
                <TableCell>强度</TableCell>
                <TableCell>平台</TableCell>
                <TableCell>Draft Hold</TableCell>
                <TableCell>状态</TableCell>
                <TableCell>创建时间</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {filtered.map(a => (
                <TableRow key={a.alertId} hover>
                  <TableCell><code>{a.alertId.slice(0, 12)}...</code></TableCell>
                  <TableCell>{a.agentId}</TableCell>
                  <TableCell>
                    <Chip label={a.polarity} size="small"
                      sx={{ bgcolor: getPolarityColor(a.polarity), color: '#fff' }} />
                  </TableCell>
                  <TableCell>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                      <LinearProgress variant="determinate" value={a.intensity}
                        sx={{ width: 60, height: 6, borderRadius: 3,
                          '& .MuiLinearProgress-bar': { bgcolor: a.intensity > 70 ? '#f44336' : '#ff9800' } }} />
                      <Typography variant="caption">{a.intensity}</Typography>
                    </Box>
                  </TableCell>
                  <TableCell>{a.platform}</TableCell>
                  <TableCell>
                    {a.draftHoldTriggered ?
                      <Chip label="HOLD" size="small" color="warning" /> :
                      <Chip label="-" size="small" />}
                  </TableCell>
                  <TableCell><Chip label={a.status} size="small" color={getStatusColor(a.status) as any} /></TableCell>
                  <TableCell>{new Date(a.createdAt * 1000).toLocaleString()}</TableCell>
                </TableRow>
              ))}
              {filtered.length === 0 && (
                <TableRow><TableCell colSpan={8} align="center">暂无舆情预警</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      )}
    </Box>
  );
};

/** ITA触发链路Tab */
const ITAChainTab: React.FC = () => {
  const [chains, setChains] = useState<ITATriggerChain[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await apiClient.get('/v14/sentiment-ita/ita-chains');
      if (res.data?.code === 0) setChains(res.data.data || []);
    } catch (err) { console.error(err); }
    setLoading(false);
  };

  useEffect(() => { fetchData(); }, []);

  return (
    <Box>
      <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="subtitle2">ITA触发链路 (Information → Trigger → Action)</Typography>
        <Button size="small" onClick={fetchData} disabled={loading}>刷新</Button>
      </Box>
      {loading ? <LinearProgress /> : (
        <Grid container spacing={2}>
          {chains.map(chain => (
            <Grid item xs={12} md={6} key={chain.chainId}>
              <Card variant="outlined">
                <CardContent>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                    <Typography variant="subtitle2">{chain.chainId.slice(0, 16)}...</Typography>
                    <Chip label={chain.status} size="small"
                      color={chain.status === 'COMPLETED' ? 'success' : chain.status === 'FIRING' ? 'warning' : 'default'} />
                  </Box>
                  <Divider sx={{ my: 1 }} />
                  <Typography variant="caption" color="text.secondary">信息源</Typography>
                  <Typography variant="body2">{chain.information.type} @ {chain.information.source}</Typography>
                  <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>触发条件</Typography>
                  <Typography variant="body2" sx={{ fontFamily: 'monospace', fontSize: '0.8rem' }}>
                    {chain.trigger.expression}
                  </Typography>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 0.5 }}>
                    <LinearProgress variant="determinate"
                      value={Math.min(100, (chain.trigger.currentValue / chain.trigger.thresholdValue) * 100)}
                      sx={{ flex: 1, height: 6 }} />
                    <Typography variant="caption">
                      {chain.trigger.currentValue.toFixed(1)} / {chain.trigger.thresholdValue}
                    </Typography>
                  </Box>
                  <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>动作链</Typography>
                  {chain.actions.map((act, i) => (
                    <Box key={act.id} sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 0.5 }}>
                      <Typography variant="caption" color="text.secondary">{i + 1}.</Typography>
                      <Typography variant="body2" sx={{ flex: 1 }}>{act.type}</Typography>
                      <Chip label={act.status} size="small"
                        color={act.status === 'COMPLETED' ? 'success' : 'default'} />
                    </Box>
                  ))}
                </CardContent>
              </Card>
            </Grid>
          ))}
          {chains.length === 0 && (
            <Grid item xs={12}><Alert severity="info">暂无ITA触发链路，等待舆情触发</Alert></Grid>
          )}
        </Grid>
      )}
    </Box>
  );
};

/** 补偿方案Tab */
const CompensateTab: React.FC = () => {
  const [plans, setPlans] = useState<CompensatePlan[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await apiClient.get('/v14/sentiment-ita/compensate-plans');
      if (res.data?.code === 0) setPlans(res.data.data || []);
    } catch (err) { console.error(err); }
    setLoading(false);
  };

  useEffect(() => { fetchData(); }, []);

  return (
    <Box>
      <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="subtitle2">补偿方案 (1小时内自动生成)</Typography>
        <Button size="small" onClick={fetchData} disabled={loading}>刷新</Button>
      </Box>
      {loading ? <LinearProgress /> : (
        <TableContainer component={Paper}>
          <Table size="small" stickyHeader>
            <TableHead>
              <TableRow>
                <TableCell>方案ID</TableCell>
                <TableCell>Agent</TableCell>
                <TableCell>类型</TableCell>
                <TableCell>描述</TableCell>
                <TableCell>金额</TableCell>
                <TableCell>自动生成</TableCell>
                <TableCell>已批准</TableCell>
                <TableCell>已执行</TableCell>
                <TableCell>反馈评分</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {plans.map(p => (
                <TableRow key={p.planId} hover>
                  <TableCell><code>{p.planId.slice(0, 12)}...</code></TableCell>
                  <TableCell>{p.agentId}</TableCell>
                  <TableCell><Chip label={p.compensateType} size="small" /></TableCell>
                  <TableCell sx={{ maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.description}</TableCell>
                  <TableCell>{p.amount ? `¥${p.amount}` : '-'}</TableCell>
                  <TableCell>{p.autoGenerated ? <CheckCircleIcon color="success" /> : <ErrorIcon color="disabled" />}</TableCell>
                  <TableCell>{p.approved ? <CheckCircleIcon color="success" /> : <ErrorIcon color="disabled" />}</TableCell>
                  <TableCell>{p.executed ? <CheckCircleIcon color="success" /> : <ErrorIcon color="disabled" />}</TableCell>
                  <TableCell>{p.feedbackScore ? `${p.feedbackScore}/5` : '-'}</TableCell>
                </TableRow>
              ))}
              {plans.length === 0 && (
                <TableRow><TableCell colSpan={9} align="center">暂无补偿方案</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      )}
    </Box>
  );
};

// =============== Main Panel ===============

const SentimentITAPanel: React.FC = () => {
  const [activeTab, setActiveTab] = useState(0);

  return (
    <Box>
      <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 2 }}>
        <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)}>
          <Tab label="📊 舆情监测" />
          <Tab label="🔗 ITA触发链路" />
          <Tab label="💰 补偿方案" />
        </Tabs>
      </Box>
      {activeTab === 0 && <MonitoringTab />}
      {activeTab === 1 && <ITAChainTab />}
      {activeTab === 2 && <CompensateTab />}
    </Box>
  );
};

export default SentimentITAPanel;
